# Generated by Django 4.0.3 on 2023-09-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='iha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=10)),
                ('condition', models.CharField(max_length=20)),
                ('isRented', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
