# Generated by Django 4.0.3 on 2023-09-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0003_category_iha_image_alter_iha_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha',
            old_name='isRented',
            new_name='isrented',
        ),
    ]
